//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;

//namespace WMaster
//{
//    [Obsolete("Dont use this class, need to initialise ans save configuration data outside project execution", false)]
//    public class TempConfiguration
//    {
//        private System.Collections.Specialized.NameValueCollection ResourcesText = new System.Collections.Specialized.NameValueCollection();

//        public void Initialise()
//        {
//            //ResourcesText.Add("Gang[GangName]IsAttackingRivals", "Gang   [[:GangName:]]   is attacking rivals.");
//            //ResourcesText.Add("TheyFailedToFindAnyEnemyAssetsToHit", "They failed to find any enemy assets to hit.");
//            //ResourcesText.Add("ScoutedTheCityInVainSeekingWouldbeChallengersToYourDominance", "Scouted the city in vain, seeking would-be challengers to your dominance.");
//            //ResourcesText.Add("YourMenRunIntoAGangFrom[GangName]AndABrawlBreaksOut", "Your men run into a gang from [[:GangName:]] and a brawl breaks out.");
//            //ResourcesText.Add("YourGang[GangName]FailsToReportBackFromTheirSabotageMissionLaterYouLearnThatTheyWereWipedOutToTheLastMan", "Your gang [[:GangName:]] fails to report back from their sabotage mission.[[:NewLine:]]Later you learn that they were wiped out to the last man.");
//            //ResourcesText.Add("YourMenLostTheLoneSurvivorFightsHisWayBackToFriendlyTerritory", "Your men lost. The lone survivor fights his way back to friendly territory.");
//            //ResourcesText.Add("YourMenLostThe[GangMemberNum]SurvivorsFightTheirWayBackToFriendlyTerritory", "Your men lost. The [[:GangMemberNum:]] survivors fight their way back to friendly territory.");
//            //ResourcesText.Add("YourMenWin", "Your men win.");
//            //ResourcesText.Add("TheEnemyGangIsDestroyed[RivalName]HasNoMoreGangsLeft", "The enemy gang is destroyed. [[:RivalName:]] has no more gangs left!");
//            //ResourcesText.Add("TheEnemyGangIsDestroyed[RivalName]HasAFewGangsLeft", "The enemy gang is destroyed. [[:RivalName:]] has a few gangs left.");
//            //ResourcesText.Add("TheEnemyGangIsDestroyed[RivalName]HasALotOfGangsLeft", "The enemy gang is destroyed. [[:RivalName:]] has a lot of gangs left.");
//            //ResourcesText.Add("YourMenEncounterNoResistanceWhenYouGoAfter[RivalGangName]", "Your men encounter no resistance when you go after [[:RivalGangName:]].");
//            //ResourcesText.Add("YourMenDestroy[Number]OfTheirBusinesses[RivalName]HaveNoMoreBusinessesLeft", "Your men destroy [[:Number:]] of their businesses. [[:RivalName:]] have no more businesses left!");
//            //ResourcesText.Add("YourMenDestroy[Number]OfTheirBusinesses[RivalName]HaveAFewBusinessesLeft", "Your men destroy [[:Number:]] of their businesses. [[:RivalName:]] have a few businesses left.");
//            //ResourcesText.Add("YourMenDestroy[Number]OfTheirBusinesses[RivalName]HaveALotOfBusinessesLeft", "Your men destroy [[:Number:]] of their businesses. [[:RivalName:]] have a lot of businesses left.");
//            //ResourcesText.Add("[RivalName]HaveNoBusinessesToAttack", "[[:RivalName:]] have no businesses to attack.");
//            //ResourcesText.Add("YourMenSteal[GoldAmount]GoldFromThemMuhahahaha[RivalName]IsPennilessNow", "Your men steal [[:GoldAmount:]] gold from them. Mu-hahahaha!  [[:RivalName:]] is penniless now!");
//            //ResourcesText.Add("YourMenSteal[GoldAmount]GoldFromThem[RivalName]IsLookingPrettyPoor", "Your men steal [[:GoldAmount:]] gold from them. [[:RivalName:]] is looking pretty poor.");
//            //ResourcesText.Add("YourMenSteal[GoldAmount]GoldFromThemItLooksLike[RivalName]StillHasALotOfGold", "Your men steal [[:GoldAmount:]] gold from them. It looks like [[:RivalName:]] still has a lot of gold.");
//            //ResourcesText.Add("AsYourMenAreFleeingOneOfThemHasToJumpThroughAWallOfFireWhenHeDoesHeDropsAGoldBearerBondWorth10kGoldEach[BurnedBondsCost]GoldJustWentUpInSmoke", "As your men are fleeing, one of them has to jump through a wall of fire. When he does, he drops a Gold Bearer Bond worth 10k gold each. [[:BurnedBondsCost:]] gold just went up in smoke.");
//            //ResourcesText.Add("AsYourMenAreFleeingOneOfThemHasToJumpThroughAWallOfFireWhenHeDoesHeDropsAStackOfGoldBearerBondsWorth10kGoldEach[BurnedBondsCost]GoldJustWentUpInSmoke", "As your men are fleeing, one of them has to jump through a wall of fire. When he does, he drops a stack of Gold Bearer Bonds worth 10k gold each. [[:BurnedBondsCost:]] gold just went up in smoke.");
//            //ResourcesText.Add("AsYourMenAreFleeingOneOfThemHasToJumpThroughAWallOfFireWhenHeDoesHeDrops[BurnedBonds]GoldBearerBondsWorth10kGoldEach[BurnedBondsCost]GoldJustWentUpInSmoke", "As your men are fleeing, one of them has to jump through a wall of fire. When he does, he drops [[:BurnedBonds:]] Gold Bearer Bonds worth 10k gold each. [[:BurnedBondsCost:]] gold just went up in smoke.");
//            //ResourcesText.Add("AsTheyAreBeingChasedThroughTheStreetsBy[RivalName]sPeopleOneOfYourGangMembersCutsOpenASackOfGoldSpillingItsContentsInTheStreetAsTheThrongsOfCiviliansStreamInToCollectTheCoinsTheyBlockThePursuersAndAllowYouMenToGetAwaySafely", "As they are being chased through the streets by [[:RivalName:]]'s people, one of your gang members cuts open a sack of gold spilling its contents in the street. As the throngs of civilians stream in to collect the coins, they block the pursuers and allow you men to get away safely.");
//            //ResourcesText.Add("AsYourGangLeaveYourRivalsTerritoryOnTheWayBackToYourBrothelTheyComeUponABandOfLocalPoliceThatAreHuntingThemTheirBossDemands[BribePercent]OfWhatYourGangIsCarryingInOrderToLetThemGoTheyPayThem[Bribe]GoldAndContinueOnHome", "As your gang leave your rival's territory on the way back to your brothel, they come upon a band of local police that are hunting them. Their boss demands [[:BribePercent:]]% of what your gang is carrying in order to let them go. They pay them [[:Bribe:]] gold and continue on home.");
//            //ResourcesText.Add("[GangName]ReturnsWith[GoldAmount]Gold", "[[:GangName:]] returns with [[:GoldAmount:]] gold.");
//            //ResourcesText.Add("TheLosersHaveNoGoldToTake", "The losers have no gold to take.");
//            //ResourcesText.Add("YourMenStealAnItemFromThemOne[ItemName]", "Your men steal an item from them, one [[:ItemName:]].");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sBrothels[RivalName]HasNoBrothelsLeft", "Your men burn down one of [[:RivalName:]]'s Brothels. [[:RivalName:]] has no Brothels left.");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sBrothels[RivalName]IsInControlOfVeryFewBrothels", "Your men burn down one of [[:RivalName:]]'s Brothels. [[:RivalName:]] is in control of very few Brothels.");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sBrothels[RivalName]HasManyBrothelsLeft", "Your men burn down one of [[:RivalName:]]'s Brothels. [[:RivalName:]] has many Brothels left.");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sGamblingHalls[RivalName]HasNoGamblingHallsLeft", "Your men burn down one of [[:RivalName:]]'s Gambling Halls. [[:RivalName:]] has no Gambling Halls left.");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sGamblingHalls[RivalName]IsInControlOfVeryFewGamblingHalls", "Your men burn down one of [[:RivalName:]]'s Gambling Halls. [[:RivalName:]] is in control of very few Gambling Halls.");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sGamblingHalls[RivalName]HasManyGamblingHallsLeft", "Your men burn down one of [[:RivalName:]]'s Gambling Halls. [[:RivalName:]] has many Gambling Halls left.");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sBars[RivalName]HasNoBarsLeft", "Your men burn down one of [[:RivalName:]]'s Bars. [[:RivalName:]] has no Bars left.");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sBars[RivalName]IsInControlOfVeryFewBars", "Your men burn down one of [[:RivalName:]]'s Bars. [[:RivalName:]] is in control of very few Bars");
//            //ResourcesText.Add("YourMenBurnDownOneOf[RivalName]sBars[RivalName]HasManyBarsLeft", "Your men burn down one of [[:RivalName:]]'s Bars. [[:RivalName:]] has many Bars left");
//            //ResourcesText.Add("Gang[GangName]IsLookingForEscapedGirls", "Gang   [[:GangName:]]   is looking for escaped girls.");
//            //ResourcesText.Add("ThereAreNoneOfYourGirlsWhoHaveRunAwaySoTheyHaveNooneToLookFor", "There are none of your girls who have run away, so they have noone to look for.");
//            //ResourcesText.Add("YourGoonsFind[GirlName]AndSheComesQuietlyWithoutPuttingUpAFight", "Your goons find [[:GirlName:]] and she comes quietly without putting up a fight.");
//            //ResourcesText.Add("YourGoonsFind[GirlName]AndTheyTryToCatchHerInTheirNets", "Your goons find [[:GirlName:]] and they try to catch her in their nets.");
//            //ResourcesText.Add("[GirlName]WasRecapturedBy[GangName]SheGaveUpWithoutAFight", "[[:GirlName:]] was recaptured by [[:GangName:]]. She gave up without a fight.");
//            //ResourcesText.Add("[GirlName]ManagedToDamage[Number]OfTheirNetsBeforeTheyFinallyCaughtHerInTheTatteredRemainsOfTheirLastNet", "[[:GirlName:]] managed to damage [[:Number:]] of their nets before they finally caught her in the tattered remains of their last net.");
//            //ResourcesText.Add("[GirlName]ManagedToDamage[Number]OfTheirNetsBeforeTheyFinallyCaughtHerInTheirLastNet", "[[:GirlName:]] managed to damage [[:Number:]] of their nets before they finally caught her in their last net.");
//            //ResourcesText.Add("[GirlName]ManagedToDamage[Number]OfTheirNetsBeforeTheyFinallyCaughtHerInTheirNets", "[[:GirlName:]] managed to damage [[:Number:]] of their nets before they finally caught her in their nets.");
//            //ResourcesText.Add("SheStrugglesAgainstTheNetYourMenUseButItIsPointlessSheIsInYourDungeonNow", "She struggles against the net your men use, but it is pointless. She is in your dungeon now.");
//            //ResourcesText.Add("[GirlName]WasCapturedInANetAndDraggedBackToTheDungeonBy[GangName]", "[[:GirlName:]] was captured in a net and dragged back to the dungeon by [[:GangName:]].");
//            //ResourcesText.Add("[GirlName]ManagedToDamageAllOfTheirNetsSoTheyHaveToDoThingsTheHardWay", "[[:GirlName:]] managed to damage all of their nets so they have to do things the hard way.");
//            //ResourcesText.Add("[GangName]AttemptToRecaptureHer", "[[:GangName:]] attempt to recapture her.");
//            //ResourcesText.Add("SheFightsBackButYourMenSucceedInCapturingHer", "She fights back but your men succeed in capturing her.");
//            //ResourcesText.Add("[GirlName]FoughtWith[GangName]ButLostSheWasDraggedBackToTheDungeon", "[[:GirlName:]] fought with [[:GangName:]] but lost. She was dragged back to the dungeon.");
//            //ResourcesText.Add("TheGirlFightsBackAndDefeatsYourMenBeforeEscapingIntoTheStreets", "The girl fights back and defeats your men before escaping into the streets.");
//            //ResourcesText.Add("[GangName]RecaptureHerSuccessfullyWithoutAFussSheIsInYourDungeonNow", "[[:GangName:]] recapture her successfully without a fuss. She is in your dungeon now.");
//            //ResourcesText.Add("[GirlName]WasSurroundedBy[GangName]AndGaveUpWithoutAFight", "[[:GirlName:]] was surrounded by [[:GangName:]] and gave up without a fight.");
//            //ResourcesText.Add("AfterDodgingAllOfTheirNetsSheGivesUpWhenTheyPullOutTheirWeaponsAndPrepareToKillHer", "After dodging all of their nets, she gives up when they pull out their weapons and prepare to kill her.");
//            //ResourcesText.Add("[GirlName]WasSurroundedBy[GangName]AndGaveUpWithoutAnymoreOfAFight", "[[:GirlName:]] was surrounded by [[:GangName:]] and gave up without anymore of a fight.");
//            //ResourcesText.Add("Gang[GangName]IsCapturingTerritory", "Gang   [[:GangName:]]   is capturing territory.");
//            //ResourcesText.Add("TheyFailToGainAnyMoreNeutralTerritories", "They fail to gain any more neutral territories.");
//            //ResourcesText.Add("YouGainControlOfOneMoreNeutralTerritories", "You gain control of one more neutral territories.");
//            //ResourcesText.Add("YouGainControlOf[Number]MoreNeutralTerritory", "You gain control of [[:Number:]] more neutral territory.");
//            //ResourcesText.Add("ThereAreNoMoreUncontrolledBusinessesLeft", "There are no more uncontrolled businesses left.");
//            //ResourcesText.Add("ThereIsOneUncontrolledBusinessesLeft", "There is one uncontrolled businesses left.");
//            //ResourcesText.Add("ThereAreUncontrolledBusinessesLeft", "There are uncontrolled businesses left.");
//            //ResourcesText.Add("TheyStormIntoYourRival[RivalName]sTerritory", "They storm into your rival [[:RivalName:]]'s territory.");
//            //ResourcesText.Add("YourMenRunIntoOneOfTheirGangsAndABrawlBreaksOut", "Your men run into one of their gangs and a brawl breaks out.");
//            //ResourcesText.Add("TheyDestroyTheDefendersAnd", "They destroy the defenders and ");
//            //ResourcesText.Add("TheyDefeatTheDefendersAnd", "They defeat the defenders and ");
//            //ResourcesText.Add("TheyFacedNoOppositionAsThey", "They faced no opposition as they ");
//            //ResourcesText.Add("YourGangHasBeenDefeatedAndFailToTakeControlOfAnyNewTerritory", "Your gang has been defeated and fail to take control of any new territory.");
//            //ResourcesText.Add("TookOverOneOf[RivalName]sTerritory", "took over one of [[:RivalName:]]'s territory.");
//            //ResourcesText.Add("TookOver[Number]Of[RivalName]sTerritories", "took over [[:Number:]] of [[:RivalName:]]'s territories.");
//            //ResourcesText.Add("LeftErrorNoTerritoriesGainedButShouldHaveBeen", "left. (Error: no territories gained but should have been)");
//            //ResourcesText.Add("YouFailToTakeControlOfAnyOfNewTerritories", "You fail to take control of any of new territories.");
//            //ResourcesText.Add("Gang[GangName]IsPerformingPettyTheft", "Gang   [[:GangName:]]   is performing petty theft.");
//            //ResourcesText.Add("YourMenRunIntoAGangFrom[RivalName]AndABrawlBreaksOut", "Your men run into a gang from [[:RivalName:]] and a brawl breaks out.");
//            //ResourcesText.Add("YourMenRunIntoGroupOfThugsFromTheStreetsAndABrawlBreaksOut", "Your men run into group of thugs from the streets and a brawl breaks out.");
//            //ResourcesText.Add("YourMenLoseTheFight", "Your men lose the fight.");
//            //ResourcesText.Add("YourMenAreConfrontedByAMaskedVigilante", "Your men are confronted by a masked vigilante.");
//            //ResourcesText.Add("SheFightsWellButYourMenStillManageToCaptureHer", "She fights well but your men still manage to capture her");
//            //ResourcesText.Add("SheFightsYourMenButLosesQuickly", "She fights your men but loses quickly");
//            //ResourcesText.Add("SheFightsYourMenButTheyTakeHerDownWithOnlyOneCasualty", "She fights your men but they take her down with only one casualty");
//            //ResourcesText.Add("SheFightsYourMenButTheyTakeHerDownWithOnlyAFewCasualties", "She fights your men but they take her down with only a few casualties");
//            //ResourcesText.Add("TheyUnmask[GirlName]TakeAllHerGold[Number]FromHerAndDragHerToTheDungeon", "They unmask [[:GirlName:]], take all her gold ([[:Number:]]) from her and drag her to the dungeon.");
//            //ResourcesText.Add("[GirlName]TriedToStop[GangName]FromComittingPettyTheftButLostSheWasDraggedBackToTheDungeon", "[[:GirlName:]] tried to stop [[:GangName:]] from comitting petty theft but lost. She was dragged back to the dungeon.");
//            //ResourcesText.Add("SheDefeatsYourMenAndDisappearsBackIntoTheShadows", "She defeats your men and disappears back into the shadows.");
//            //ResourcesText.Add("ThisGangWasSentToLookForRunawaysButThereAreNoneSoTheyWentLookingForAnyGirlToKidnapInstead", "This gang was sent to look for runaways but there are none so they went looking for any girl to kidnap instead.");
//            //ResourcesText.Add("ErrorNoMissionSetOrMissionNotFound[MissionName]", "Error: no mission set or mission not found: [[:MissionName:]]");
//            //ResourcesText.Add("YouHaveDealt[RivalName]AFatalBlowTheirCriminalOrganizationCrumblesToNothingBeforeYou", "You have dealt [[:RivalName:]] a fatal blow. Their criminal organization crumbles to nothing before you.");
//            //ResourcesText.Add("WhoPeople", "people");
//            //ResourcesText.Add("WhoKids", "kids");
//            //ResourcesText.Add("WhoLittleOldLadies", "little old ladies");
//            //ResourcesText.Add("WhoNobleMenAndWomen", "noble men and women");
//            //ResourcesText.Add("WhoSmallStalls", "small stalls");
//            //ResourcesText.Add("WhoTraders", "traders");
//            //ResourcesText.Add("YourGangRobs[NumberWho][Who]AndGet[NumberGold]GoldFromThem", "Your gang robs [[:NumberWho:]] [[:Who:]] and get [[:NumberGold:]] gold from them.");
//            //ResourcesText.Add("[GangName]LostOneMan", "[[:GangName:]] lost one man.");
//            //ResourcesText.Add("[GangName]Lost[Number]Men", "[[:GangName:]] lost [[:Number:]] men.");
//            //ResourcesText.Add("PlacePlace", "place");
//            //ResourcesText.Add("PlaceSmallShop", "small shop");
//            //ResourcesText.Add("PlaceSmithy", "smithy");
//            //ResourcesText.Add("PlaceJeweler", "jeweler");
//            //ResourcesText.Add("PlaceTradeCaravan", "trade caravan");
//            //ResourcesText.Add("PlaceBank", "bank");
//            //ResourcesText.Add("Gang[GangName]GoesOutToRobA[ThievePlace]", "Gang   [[:GangName:]]   goes out to rob a [[:ThievePlace:]].");
//            //ResourcesText.Add("The[ThievePlace]IsGuardedByAGangFrom[RivalName]", "The [[:ThievePlace:]] is guarded by a gang from [[:RivalName:]].");
//            //ResourcesText.Add("The[ThievePlace]HasItsOwnGuards", "The [[:ThievePlace:]] has its own guards.");
//            //ResourcesText.Add("The[ThievePlace]IsUnguarded", "The [[:ThievePlace:]] is unguarded");
//            //ResourcesText.Add("TheyGetAwayWith[Number]GoldFromThe[ThievePlace]", "They get away with [[:Number:]] gold from the [[:ThievePlace:]].");
//            //ResourcesText.Add("Gang[GangName]IsKidnappingGirls", "Gang   [[:GangName:]]   is kidnapping girls.");
//            //ResourcesText.Add("YourMenFindAGirl[GirlName]AndConvinceHerThatSheShouldWorkForYou", "Your men find a girl, [[:GirlName:]], and convince her that she should work for you.");
//            //ResourcesText.Add("YourMenFindAGirl[GirlName]AndTryToCatchHerInTheirNets", "Your men find a girl, [[:GirlName:]], and try to catch her in their nets.");
//            //ResourcesText.Add("YourMenFindAGirl[GirlName]AndAttemptToKidnapHer", "Your men find a girl, [[:GirlName:]], and attempt to kidnap her.");
//            //ResourcesText.Add("[GirlName]WasTalkedIntoWorkingForYouBy[GangName]", "[[:GirlName:]] was talked into working for you by [[:GangName:]].");
//            //ResourcesText.Add("SheFightsBackButYourMenSucceedInKidnappingHer", "She fights back but your men succeed in kidnapping her.");
//            //ResourcesText.Add("[GangName]KidnapHerSuccessfullyWithoutAFussSheIsInYourDungeonNow", "[[:GangName:]] kidnap her successfully without a fuss. She is in your dungeon now.");
//            //ResourcesText.Add("TheyFailedToFindAnyGirlsToKidnap", "They failed to find any girls to kidnap.");
//            //ResourcesText.Add("Gang[GangName]IsExploringTheCatacombs", "Gang   [[:GangName:]]   is exploring the catacombs.");
//            //ResourcesText.Add("YouTellThemToGetWhateverTheyCanFind", "You tell them to get whatever they can find.");
//            //ResourcesText.Add("All[Number]OfThemReturn", "All [[:Number:]] of them return.");
//            //ResourcesText.Add("[Number]OfThe[GangNumber]WhoWentOutReturn", "[[:Number:]] of the [[:GangNumber:]] who went out return.");
//            //ResourcesText.Add("TheyBringBackWithThem[Number]Gold", "They bring back with them:   [[:Number:]] gold");
//            //ResourcesText.Add("YourInventoryIsFull", "Your inventory is full");
//            //ResourcesText.Add("One[ItemName]", "one [[:ItemName:]]");
//            //ResourcesText.Add("YourMenAlsoCapturedAGirlNamed[GirlName]", "Your men also captured a girl named [[:GirlName:]]");
//            //ResourcesText.Add("[GirlName]WasCapturedInTheCatacombsBy[GangName]", "[[:GirlName:]] was captured in the catacombs by [[:GangName:]]");
//            //ResourcesText.Add("YourMenAlsoCapturedAGirl", "Your men also captured a girl.");
//            //ResourcesText.Add("YourMenAlsoBringBack[Number]Beasts", "Your men also bring back [[:Number:]] beasts.");
//            //ResourcesText.Add("YourMenCapturedOneGirl", "Your men captured one girl:");
//            //ResourcesText.Add("YourMenCaptured[Number]Girls", "Your men captured [[:Number:]] girls:");
//            //ResourcesText.Add("Unique", "   (unique)");
//            //ResourcesText.Add("YourMenBringBackOneItem", "Your men bring back one item:");
//            //ResourcesText.Add("YourMenBringBack[Number]Items", "Your men bring back [[:Number:]] items:");
//            //ResourcesText.Add("YourMenBringBack[Number]Beasts", "Your men bring back [[:Number:]] beasts.");
//            //ResourcesText.Add("Gang[GangName]SpendTheWeekHelpingOutTheCommunity", "Gang   [[:GangName:]]   spend the week helping out the community.");
//            //ResourcesText.Add("ALocalBoyDecidedToJoinYourGangToHelpOutTheirCommunity", "A local boy decided to join your gang to help out their community.");
//            //ResourcesText.Add("TwoLocalsDecidedToJoinYourGangToHelpOutTheirCommunity", "Two locals decided to join your gang to help out their community.");
//            //ResourcesText.Add("SomeLocalsDecidedToJoinYourGangToHelpOutTheirCommunity", "Some locals decided to join your gang to help out their community.");
//            //ResourcesText.Add("TheyCleanedUpAround[BrothelName]FixingLightsRemovingDebrisAndMakingSureTheAreaIsSecure", "They cleaned up around [[:BrothelName:]] fixing lights, removing debris and making sure the area is secure.");
//            //ResourcesText.Add("TheyRoundedUpAStrayBeastAndBroughtItToTheBrothel", "They rounded up a stray beast and brought it to the brothel.");
//            //ResourcesText.Add("TheyRoundedUpTwoStrayBeastsAndBroughtThemToTheBrothel", "They rounded up two stray beasts and brought them to the brothel.");
//            //ResourcesText.Add("TheyRoundedUpSomeStrayBeastsAndBroughtThemToTheBrothel", "They rounded up some stray beasts and brought them to the brothel.");
//            //ResourcesText.Add("BrothelSecurity", "Security");
//            //ResourcesText.Add("GlobalBeasts", "Beasts");
//            //ResourcesText.Add("PlayerSuspicion", "Suspicion");
//            //ResourcesText.Add("PlayerCustomerFear", "Customer Fear");
//            //ResourcesText.Add("PlayerDisposition", "Disposition");
//            //ResourcesText.Add("AttributeService", "Service");
//            //ResourcesText.Add("AttributeCharisma", "Charisma");
//            //ResourcesText.Add("AttributeIntelligence", "Intelligence");
//            //ResourcesText.Add("AttributeAgility", "Agility");
//            //ResourcesText.Add("AttributeMagic", "Magic");
//            //ResourcesText.Add("TheyRecieved[Number]GoldInTipsFromGratefulPeople", "They recieved [[:Number:]] gold in tips from grateful people.");
//            //ResourcesText.Add("Gang[GangName]SpendTheWeekTrainingAndImprovingTheirSkills", "Gang   [[:GangName:]]   spend the week training and improving their skills.");
//            //ResourcesText.Add("AttributeCombat", "Combat");
//            //ResourcesText.Add("AttributeToughness", "Toughness");
//            //ResourcesText.Add("AttributeStrength", "Strength");
//            //ResourcesText.Add("Gang[GangName]IsRecruiting", "Gang   [[:GangName:]]   is recruiting.");
//            //ResourcesText.Add("TheyWereUnableToFindAnyoneToRecruit", "They were unable to find anyone to recruit.");
//            //ResourcesText.Add("TheyFoundOnePersonToTryToRecruit", "They found one person to try to recruit");
//            //ResourcesText.Add("TheyFoundPeopleToTryToRecruit", "They found people to try to recruit");
//            //ResourcesText.Add("AndTheyGotHimToJoin", " and they got him to join.");
//            //ResourcesText.Add("ButHeDidntWantToJoin", " but he didn't want to join.");
//            //ResourcesText.Add("ButWereUnableToGetAnyToJoin", " but were unable to get any to join.");
//            //ResourcesText.Add("AndManagedToGetAllOfThemToJoin", " and managed to get all of them to join.");
//            //ResourcesText.Add("ButWereOnlyAbleToConvinceOneOfThemToJoin", " but were only able to convince one of them to join.");
//            //ResourcesText.Add("AndWereAbleToConvince[Number]OfThemToJoin", " and were able to convince [[:Number:]] of them to join.");
//            //ResourcesText.Add("TheyGotAsManyAsTheyNeededToFillTheirRanks", "They got as many as they needed to fill their ranks.");
//            //ResourcesText.Add("TheyOnlyHadRoomForOneMoreInTheirGangSoThey", "They only had room for one more in their gang so they ");
//            //ResourcesText.Add("TheyOnlyHadRoomFor[Number]MoreInTheirGangSoThey", "They only had room for [[:Number:]] more in their gang so they ");
//            //ResourcesText.Add("SentTheRestToJoin[GangName]", "sent the rest to join [[:GangName:]].");
//            //ResourcesText.Add("[GangName]SentOneRecruitThatTheyHadNoRoomForTo[ToGangName]", "[[:GangName:]] sent one recruit that they had no room for to [[:ToGangName:]].");
//            //ResourcesText.Add("[GangName]Sent[Number]RecruitsThatTheyHadNoRoomForTo[ToGangName]", "[[:GangName:]] sent [[:Number:]] recruits that they had no room for to [[:ToGangName:]].");
//            //ResourcesText.Add("TheyArrived", "They arrived ");
//            //ResourcesText.Add("TheyAllArrived", "They all arrived ");
//            //ResourcesText.Add("Only[Number]Arrived", "Only [[:Number:]] arrived ");
//            //ResourcesText.Add("AndGotAcceptedIntoTheGang", "and got accepted into the gang.");
//            //ResourcesText.Add("But[GangName]CouldOnlyTake[Number]OfThem", "but [[:GangName:]] could only take [[:Number:]] of them.");
//            //ResourcesText.Add("ButNoneShowedUp", " but none showed up.");
//            //ResourcesText.Add("HadToTurnAwayTheRest", " had to turn away the rest.");
//            //ResourcesText.Add("[GangName]WasLostWhile[GangMissionName]", "[[:GangName:]] was lost while [[:GangMissionName:]]");
//            //ResourcesText.Add("MissionGuarding", "guarding");
//            //ResourcesText.Add("MissionSabotage", "attacking your rivals");
//            //ResourcesText.Add("MissionSpyGirls", "spying on your girls");
//            //ResourcesText.Add("MissionRecaptureGirls", "trying to recapture a runaway");
//            //ResourcesText.Add("MissionExtortion", "trying to extort new businesses");
//            //ResourcesText.Add("MissionPettyTheft", "performing petty crimes");
//            //ResourcesText.Add("MissionGrandTheft", "performing major crimes");
//            //ResourcesText.Add("MissionKidnappGirls", "trying to kidnap girls");
//            //ResourcesText.Add("MissionCatacombs", "exploring the catacombs");
//            //ResourcesText.Add("MissionTraining", "training");
//            //ResourcesText.Add("MissionRecruit", "recruiting");
//            //ResourcesText.Add("MissionService", "helping the community");
//            //ResourcesText.Add("MissionDungeon", "doing dungeon mission");
//            //ResourcesText.Add("MissionNone", "doing nothing");
//            //ResourcesText.Add("Gang[GangName]WereSetToRecruitDueToLowNumbers", "Gang   [[:GangName:]]   were set to recruit due to low numbers.");
//            //ResourcesText.Add("Gang[GangName]WerePlacedBackOnTheirPreviousMissionNowThatTheirNumbersAreBackToNormal", "Gang   [[:GangName:]]   were placed back on their previous mission now that their numbers are back to normal.");
//            //ResourcesText.Add("Gang[GangName]WerePlacedOnGuardDutyFromRecruitmentAsTheirNumbersAreFull", "Gang   [[:GangName:]]   were placed on guard duty from recruitment as their numbers are full.");
//            //ResourcesText.Add("AllOfTheMenInGang[GangName]HaveDied", "All of the men in gang [[:GangName:]] have died.");
//            //ResourcesText.Add("Gang[GangName]IsSpyingOnYourGirls", "Gang   [[:GangName:]]   is spying on your girls.");
//            //ResourcesText.Add("Gang[GangName]IsGuarding", "Gang   [[:GangName:]]   is guarding.");
//            //ResourcesText.Add("TitleEventTypeDayShift", "Day Shift");
//            //ResourcesText.Add("TitleEventTypeNightShift", "Night Shift");
//            //ResourcesText.Add("TitleEventTypeWarning", "Warning");
//            //ResourcesText.Add("TitleEventTypeDanger", "!!!DANGER!!!");
//            //ResourcesText.Add("TitleEventTypeGoodNews", "!!!GOODNEWS!!!");
//            //ResourcesText.Add("TitleEventTypeSummary", "Summary");
//            //ResourcesText.Add("TitleEventTypeDungeon", "Dungeon");
//            //ResourcesText.Add("TitleEventTypeMatron", "Matron");
//            //ResourcesText.Add("TitleEventTypeGang", "Gang Report");
//            //ResourcesText.Add("TitleEventTypeBrothel", "Brothel");
//            //ResourcesText.Add("TitleEventTypeNoWork", "Refused Job");
//            //ResourcesText.Add("TitleEventTypeBackToWork", "Back to Work");
//            //ResourcesText.Add("TitleEventTypeLevelUp", "!!!LEVEL UP!!!");
//            //ResourcesText.Add("TitleEventTypeDebug", "#DEBUG#");
//            //ResourcesText.Add("TheLocalAuthoritiesPerformABustOnYourOperations", "The local authorities perform a bust on your operations: ");
//            //ResourcesText.Add("TheGuardCaptainLecturesYouOnTheImportanceOfCrimePreventionWhilstAlsoPassingOnTheMayorsHeartfeltBestWishes", "the guard captain lectures you on the importance of crime prevention, whilst also passing on the Mayor's heartfelt best wishes.");
//            //ResourcesText.Add("TheGuardCaptainCondemnsYourOperationAsAHotbedOfCriminalActivityAndFinesYou[Fine]GoldForLivingWithoutDueCareAndAttention", "the guard captain condemns your operation as a hotbed of criminal activity and fines you [[:Fine:]] gold for 'living without due care and attention'.");
//            //ResourcesText.Add("OnHisWayOutTheCaptainSmilesAndSaysThatThe[RivalName]SendTheirRegards", "On his way out the captain smiles and says that the [[:RivalName:]] send their regards.");
//            //ResourcesText.Add("TheyPronounceYourOperationToBeEntirelyInAccordanceWithTheLaw", "they pronounce your operation to be entirely in accordance with the law.");
//            //ResourcesText.Add("TheyFindYouInTechnicalViolationOfSomeHealthAndSafetyOrdinancesAndTheyFineYou[Fine]Gold", "they find you in technical violation of some health and safety ordinances, and they fine you [[:Fine:]] gold.");
//            //ResourcesText.Add("TheyFindSomeMinorCriminalitiesAndFineYou[Fine]Gold", "they find some minor criminalities and fine you [[:Fine:]] gold.");
//            //ResourcesText.Add("TheyFindEvidenceOfDodgyDealingsAndFineYou[Fine]Gold", "they find evidence of dodgy dealings and fine you [[:Fine:]] gold.");
//            //ResourcesText.Add("TheyFindALotOfIllegalActivitiesAndFineYou[Fine]GoldItAlsoCostsYouAnExtra[Bribe]ToPayThemOffFromArrestingYou", "they find a lot of illegal activities and fine you [[:Fine:]] gold, it also costs you an extra [[:Bribe:]] to pay them off from arresting you.");
//            //ResourcesText.Add("TheyFindEnoughDirtToPutYouBehindBarsForLifeItCostsYou[Bribe]ToStayOutOfPrisonPlusAnother[Fine]InFinesOnTopOfThat", "they find enough dirt to put you behind bars for life. It costs you [[:Bribe:]] to stay out of prison, plus another [[:Fine:]] in fines on top of that.");
//            //ResourcesText.Add("TheCaptainDeclaresYourPremisesToBeASinkholeOfTheUtmostViceAndDepravityAndItIsOnlyWithDifficultyThatYouDissuadeHimFromSeizingAllYourPropertyOnTheSpotYouPay[Fine]GoldInFinesButOnlyAfterSlippingTheCaptain[Bribe]NotToDragYouOffToPrison", "the captain declares your premises to be a sinkhole of the utmost vice and depravity, and it is only with difficulty that you dissuade him from seizing all your property on the spot. You pay [[:Fine::] gold in fines, but only after slipping the captain [[:Bribe::] not to drag you off to prison.");
//            //ResourcesText.Add("[GirlName]HasDiedFromHerInjuriesTheOtherGirlsAllFearAndHateYouALittleMore", "[[:GirlName:]] has died from her injuries, the other girls all fear and hate you a little more.");
//            //ResourcesText.Add("[GirlName]HasDiedFromHerInjuriesHerBodyWillBeRemovedByTheEndOfTheWeek", "[[:GirlName:]] has died from her injuries.  Her body will be removed by the end of the week.");
//            //ResourcesText.Add("[TotalCustomers]CustomersVisitedTheBuilding", "[[:TotalCustomers:]] customers visited the building.");
//            //ResourcesText.Add("[RejectCustomersRestrict]WereTurnedAwayBecauseOfYourSexRestrictions", "[[:RejectCustomersRestrict:]] were turned away because of your sex restrictions.");
//            //ResourcesText.Add("[RejectCustomersDisease]WereTurnedAwayBecauseTheyHadAnSTD", "[[:RejectCustomersDisease:]] were turned away because they had an STD.");
//            //ResourcesText.Add("YourAdvertisingBudgetForThisBrothelIs[AdvertisingBudget]Gold", "Your advertising budget for this brothel is [[:AdvertisingBudget:]] gold.");
//            //ResourcesText.Add("HoweverDueToYourConfigurationYouInsteadHadToPay[AdvertisingCosts]Gold", " However, due to your configuration, you instead had to pay [[:AdvertisingCosts:]] gold.");
//            //ResourcesText.Add("YouKeepARegularStockOf[Number]AntiPregnancyPotionsInThisBrothel", "You keep a regular stock of [[:Number:]] Anti-Pregnancy potions in this brothel.");
//            //ResourcesText.Add("YouHaveAStockOf[Number]AntiPregnancyPotionsInThisBrothel", "You have a stock of [[:Number:]] Anti-Pregnancy potions in this brothel.");
//            //ResourcesText.Add("YouHadAStockOf[Number]AntiPregnancyPotionsInThisBrothel", "You had a stock of [[:Number:]] Anti-Pregnancy potions in this brothel.");
//            //ResourcesText.Add("YouHaveNoAntiPregnancyPotionsInThisBrothel", "You have no Anti-Pregnancy potions in this brothel.");
//            //ResourcesText.Add("NoneWereUsed", "None were used.");
//            //ResourcesText.Add("AllHaveBeenUsed", "All have been used.");
//            //ResourcesText.Add("[Number]WereNeededThisWeek", "[[:Number:]] were needed this week.");
//            //ResourcesText.Add("[Number]WereUsedThisWeek", "[[:Number:]] were used this week.");
//            //ResourcesText.Add("[Number]WereUsedThisWeekLeaving[AntiPregNumber]InStock", "[[:Number:]] were used this week leaving [[:AntiPregNumber:]] in stock.");
//            //ResourcesText.Add("[Number]MoreThanWereInStockWereNeededSoAnEmergencyRestockHadToBeMade", "[[:Number:]] more than were in stock were needed so an emergency restock had to be made.");
//            //ResourcesText.Add("NormallyTheyCost[AntiPregPrice]GoldButOurSupplierChargesFiveTimesTheNormalPriceForUnscheduledDeliveries", "Normally they cost [[:AntiPregPrice:]] gold, but our supplier charges five times the normal price for unscheduled deliveries.");
//            //ResourcesText.Add("YourBudgetForAntiPregnancyPotionsForThisBrothelIs[Cost]Gold", "Your budget for Anti-Pregnancy potions for this brothel is [[:Cost:]] gold.");
//            //ResourcesText.Add("TheMatronOfThisBrothelHasIncreasedTheQuantityOfAntiPregnancyPotionsForFurtherOrdersTo[AntiPregPotions]", "The Matron of this brothel has increased the quantity of Anti-Pregnancy potions for further orders to [[:AntiPregPotions:]].");
//            //ResourcesText.Add("ARunnawaySlaveHasBeenRecapturedByTheAuthoritiesAndReturnedToYou", "A runnaway slave has been recaptured by the authorities and returned to you.");
//            //ResourcesText.Add("AManCannotPaySoHeSellsYouHisDaughter[GirlRealname]ToClearHisDebtToYou", "A man cannot pay so he sells you his daughter [[:GirlRealname:]] to clear his debt to you.");
//            //ResourcesText.Add("[GirlRealname]sFatherCouldNotPayHisDebtToYouSoHeGaveHerToYouAsPayment", "[[:GirlRealname:]]'s father could not pay his debt to you so he gave her to you as payment.");
//            //ResourcesText.Add("YouGain[Gold]GoldFromThe[NumBusinessExtorted]BusinessesUnderYourControl", "You gain [[:Gold:]] gold from the [[:NumBusinessExtorted:]] businesses under your control.");
//            //ResourcesText.Add("YourBrothelHadAnOverallDeficitOf[Deficit]Gold", "Your brothel had an overall deficit of [[:Deficit:]] gold.");
//            //ResourcesText.Add("YouMadeAOverallProfitOf[Profit]Gold", "You made a overall profit of [[:Profit:]] gold.");
//            //ResourcesText.Add("YouAreBreakingEvenMadeAsMuchMoneyAsYouSpent", "You are breaking even (made as much money as you spent).");
//            //ResourcesText.Add("TheMatronPuts[GirlName]BackToWork", "The Matron puts [[:GirlName:]] back to work.");
//            //ResourcesText.Add("WARNING[GirlName]IsDoingNothing", "WARNING [[:GirlName:]] is doing nothing!");
//            //ResourcesText.Add("[GirlName]WasRestingSoMadeNoMoney", "[[:GirlName:]] was resting so made no money.");
//            //ResourcesText.Add("[GirlName]ContinuedToHelpTheOtherGirlsThroughoutTheNight", "[[:GirlName:]] continued to help the other girls throughout the night.");
//            //ResourcesText.Add("YouOwnHerAndYouDontPayYourSlaves", "You own her and you don't pay your slaves.");
//            //ResourcesText.Add("[GirlName]RefusedToWorkSoMadeNoMoney", "[[:GirlName:]] refused to work so made no money.");
//            //ResourcesText.Add("[GirlName]EarnedATotalOf[TotalGold]Gold", "[[:GirlName:]] earned a total of [::TotalGold :]] gold");
//            //ResourcesText.Add("DirectlyFromYouSheGetsToKeepItAll", " directly from you. She gets to keep it all.");
//            //ResourcesText.Add("AndSheGetsToKeepItAll", " and she gets to keep it all.");
//            //ResourcesText.Add("SheKeepsThe[TotalTips]SheGotInTipsAndHerCut[AmountPercent]OfThePaymentAmountingTo[Gole]Gold", "She keeps the [[:TotalTips:]] she got in tips and her cut ([[:AmountPercent:]]%) of the payment amounting to [[:Gole:]] gold.");
//            //ResourcesText.Add("YouGot[Gold]Gold[AmountPercent]", "You got [[:Gold:]] gold ([[:AmountPercent:]]%).");
//            //ResourcesText.Add("SheKeeps[Gold]Gold[AmountPercent]", "She keeps [[:Gold:]] gold. ([[:AmountPercent:]]%).");
//            //ResourcesText.Add("YouKeep[Gold]Gold[AmountPercent]", "You keep [[:Gold:]] gold ([[:AmountPercent:]]%).");
//            //ResourcesText.Add("[GirlName]MadeNoMoney", "[[:GirlName:]] made no money.");
//            //ResourcesText.Add("ERRORSheHasALossOf[TotalGold]GoldGirlName[Realname]Job[JobName]Pay[Pay]Tips[Tips]Total[TotalGold]", "ERROR: She has a loss of [[:TotalGold:]] gold. Girl Name: [[:Realname:]], Job: [[:JobName:]], Pay: [[:Pay:]], Tips: [[:Tips:]], Total: [[:TotalGold:]]");
//            //ResourcesText.Add("PleaseReportThisToThePinkPetalDevlomentTeamAtHttppinkpetalorg", "Please report this to the Pink Petal Devloment Team at http://pinkpetal.org");
//            //ResourcesText.Add("YourMatronTakes[GirlName]OffDutyToRestDueToHerTiredness", "Your matron takes [[:GirlName:]] off duty to rest due to her tiredness.");
//            //ResourcesText.Add("YourMatronHelps[GirlName]ToRelax", "Your matron helps [[:GirlName:]] to relax.");
//            //ResourcesText.Add("CAUTIONThisGirlDesparatlyNeedRestGiveHerSomeFreeTime", "CAUTION! This girl desparatly need rest. Give her some free time.");
//            //ResourcesText.Add("YourMatronHelpsCheerUp[GirlName]AfterSheFeelsSad", "Your matron helps cheer up [[:GirlName:]] after she feels sad.");
//            //ResourcesText.Add("[GirlName]IsTakenOffDutyByYourMatronToRestDueToHerLowHealth", "[[:GirlName:]] is taken off duty by your matron to rest due to her low health.");
//            //ResourcesText.Add("YourMatronHelpsHeal[GirlName]", "Your matron helps heal [[:GirlName:]].");
//            //ResourcesText.Add("DANGER[GirlName]sHealthIsVeryLow", "DANGER [[:GirlName:]]'s health is very low!");
//            //ResourcesText.Add("SheMustRestOrSheWillDie", "She must rest or she will die!");
//        }
//    }
//}
